#pragma once
//STL
#include <iostream>
#include <cmath>
#include <vector>
#include <string>
#include <map>
#include <memory>
#include <filesystem>
#include <fstream>
#include <regex>
#include <thread>
#include <list>
#include <limits>
#include <algorithm>
#include <functional>
#include <random>
//Third Party
#include <SDL3/SDL.h>
#include <SDL3_gfx/SDL3_gfxPrimitives.h>
#include <SDL3_mixer/SDL_mixer.h>
#include <SDL3_image/SDL_image.h>
#include <SDL3_ttf/SDL_ttf.h>
#include <imgui/imgui.h>
#include <imgui/imgui_internal.h>
#include <imgui/imstb_rectpack.h>
#include <imgui/imstb_textedit.h>
#include <imgui/imstb_truetype.h>
#include <imgui/backends/imgui_impl_sdl3.h>
#include <imgui/backends/imgui_impl_sdlrenderer3.h>
#include <lua.hpp>
#include <sol/sol.hpp>
#include <rttr/type>
#include <rttr/registration.h>
#include <rttr/method.h>
#include <rttr/property.h>
#include <rttr/variant.h>
#include <rttr/array_mapper.h>
#include <cereal/cereal.hpp>
#include <cereal/types/map.hpp>
#include <cereal/types/memory.hpp>
#include <cereal/types/vector.hpp>
#include <cereal/types/array.hpp>
#include <cereal/types/string.hpp>
#include <cereal/types/list.hpp>
#include <cereal/archives/json.hpp>
#include <cereal/archives/portable_binary.hpp>
#include <box2d/box2d.h>
#include <box2d/b2_body.h>
#include <box2d/b2_fixture.h>
#include <box2d/b2_world.h>
#include <box2d/b2_polygon_shape.h>
#include <box2d/b2_circle_shape.h>
#include <box2d/b2_contact.h>
// ÏñËØ/Ã×±ÈÀý£¨30ÏñËØ=1Ã×£©
constexpr float PPM = 30.0f;

